[package]
name = "daily_art"
version = "0.1.0"
authors = ["Francois Stephany <francois@tamere.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.11.1"